name: Roulette-Kernel-Builder

on: # [push]

  workflow_dispatch:
  watch:
    types: [started]

env:
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
  KBRANCH: ${{ secrets.KBRANCH }}
  TZ: Asia/Jakarta

jobs:
  Roulette-GCC-12:

    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy-20211029

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        run: |
          apt-get update && apt-get -y upgrade
          apt-get -y install gcc llvm lld g++-multilib python2 clang git libxml2 device-tree-compiler default-jre automake lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng bc libstdc++6 libncurses5 wget python3 python3-pip libssl-dev rsync flex git-lfs libz3-dev libz3-4 axel tar binutils-dev ca-certificates ccache cmake file libelf-dev ninja-build python3-dev texinfo u-boot-tools xz-utils && python3 -m pip install networkx

      - name: Compile Kernel
        run: |
          git clone --depth=1 https://github.com/Alvinaja/kernel_xiaomi_mt6768 kernel
          cp kernel-build.sh kernel && cd kernel
          chmod +x kernel-build.sh
          bash kernel-build.sh "FullLTO"
