name: Roulette-Kernel-Builder

on: # [push]

  workflow_dispatch:
  watch:
    types: [started]

env:
  TG_TOKEN: ${{ secrets.TG_TOKEN }}
  TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
  KBRANCH: ${{ secrets.KBRANCH }}
  TZ: Asia/Jakarta

jobs:
  Roulette-GCC-12:

    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy-20211029

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile Kernel
        run: |
          git clone --depth=1 https://github.com/Alvinaja/BoreUp_Merlin kernel
          cp kernel-build.sh kernel && cd kernel
          chmod +x kernel-build.sh
          bash kernel-build.sh "FullLTO"
